### ISSUE TITLE
🐍 Bug: Tabview-Youtube moves YouTube Enhancer action bar inside video

### ISSUE THREAD

**Issue by rahaaatul** [tabview-youtube/Tabview-Youtube#53]
### ✅ [Tabview-Youtube](https://github.com/tabview-youtube/Tabview-Youtube) | ✅ [Enhancer for YouTube™](https://www.mrfdev.com/enhancer-for-youtube)

Covers the video buttons, can't access them anymore.

![image](https://github.com/user-attachments/assets/92412091-c579-4e8b-b994-eba03f4a1cc1)

### ❌ [Tabview-Youtube](https://github.com/tabview-youtube/Tabview-Youtube) | ✅ [Enhancer for YouTube™](https://www.mrfdev.com/enhancer-for-youtube)

![image](https://github.com/user-attachments/assets/6bfb52db-01e8-4e8a-8dac-2e3396c4d05a)

**Comment by cyfung1031** [comment]
removed previous css fix for Enhancer for YouTube™

please check again

**Comment by rahaaatul** [comment]
It didn't work for me. However I'd like to propose a style, here it is:

https://github.com/user-attachments/assets/9865afb7-c4bc-408a-8a97-8b750c81c1fb

Here is the code, I used:

```css
/* Fix Enhancer Action Bar */
.efyt-control-bar.centered {
	top: -1%;
	left: 50%;
	bottom: 50%;
	opacity: 0;
	filter: blur(5px);
	background-color: #0f0f0f;
	border-color: #303030;
	transition: 500ms ease;
	transition-delay: 1000ms;
}

.efyt-control-bar.centered:hover {
	top: 1%;
	transition-delay: 100ms;
	opacity: 1;
	filter: blur(0px);
}
```
